# use "yapm install ." if you're installing this from git repository

name: sinopia
version: 0.7.0
description: Private npm repository server

author:
  name: Alex Kocharin
  email: alex@kocharin.ru

repository:
  type: git
  url: git://github.com/rlidwka/sinopia

main: index.js

bin:
  sinopia: ./bin/sinopia

dependencies:
  express: '>= 3.4.7 < 4.0.0-0'
  commander: '>= 2.1.0'
  js-yaml: '>= 3.0.1'
  cookies: '>= 0.3.8'
  request: '>= 2.31.0'
  async: '>= 0.2.9'
  semver: '>= 2.2.1'
  minimatch: '>= 0.2.14'
  bunyan: '>= 0.22.1'
  fs-ext: '>= 0.3.2'
  mkdirp: '>= 0.3.5'

devDependencies:
  rimraf: '>= 2.2.5'
  mocha: '>= 1.18.0'

  # linting tools
  eslint: '>= 0.4.2'

  # validation suite for the npm registry protocol
  'registry-validator': '>=0.1.0'

  # for debugging memory leaks, it'll be require()'d if
  # installed, but I don't want it to be installed everytime
  #heapdump: '*'

keywords:
  - private
  - package
  - repository
  - registry
  - modules
  - proxy
  - server

scripts:
  test: mocha ./test/functional ./test/unit ./test/validation
  lint: eslint -c ./.eslint.yaml ./lib

# we depend on streams2 stuff
# it can be replaced with isaacs/readable-stream, ask if you need to use 0.8
engines:
  node: '>=0.10'

preferGlobal: true

# http://www.wtfpl.net/txt/copying/
license: WTFPL

